filegroup(
    name = "samples",
    srcs = [
        "add_mul.mlir",
        "dot_contracting.mlir",
        "dot_gather.mlir",
        "dot_general.mlir",
        "scaling_dot.mlir",
        "pair_scaling_dot.mlir",
        "pair_boundary_rewrite.mlir",
    ],
    visibility = ["//research/joint_shard:__subpackages__"],
)
