load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//research/joint_shard:__subpackages__"])

cc_library(
    name = "stablehlo_importer",
    srcs = ["stablehlo_importer.cc"],
    hdrs = ["stablehlo_importer.h"],
    deps = [
        "//research/joint_shard/egg-c:eggc",
        "//research/joint_shard/bridge/tensor_lang:tensorlang",
        "@llvm-project//llvm:Support",
        "@llvm-project//mlir:IR",
        "@stablehlo//:stablehlo_ops",
    ],
)

cc_library(
    name = "stablehlo_exporter",
    srcs = ["stablehlo_exporter.cc"],
    hdrs = ["stablehlo_exporter.h"],
    deps = [
        "//research/joint_shard/egg-c:eggc",
        "//research/joint_shard/bridge/tensor_lang:tensorlang",
        "@llvm-project//mlir:IR",
        "@stablehlo//:stablehlo_ops",
    ],
)
