load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//research/joint_shard:__subpackages__"])

cc_library(
    name = "tensorlang",
    srcs = [
        "attribute_rewrites.cc",
        "op_properties.cc",
        "semantic_rewrite.cc",
        "semantic_rule_application.cc",
        "semantic_rule_attributes.cc",
        "semantic_rule_guards.cc",
        "semantic_rule_internal.h",
        "semantic_rule_matcher.cc",
        "semantic_rule_validation.cc",
        "tensor_analysis.cc",
        "tensor_patterns.cc",
        "tensor_rules.cc",
        "tensorlang.cc",
    ],
    hdrs = [
        "op_properties.h",
        "tensor_analysis.h",
        "tensor_patterns.h",
        "tensor_rewrites.h",
        "tensorlang.h",
    ],
    deps = [
        "//research/joint_shard/egg-c:eggc",
        "@llvm-project//llvm:Support",
        "@llvm-project//mlir:IR",
        "@stablehlo//:stablehlo_ops",
    ],
)

cc_test(
    name = "semantic_attribute_rewrite_test",
    srcs = ["semantic_attribute_rewrite_test.cc"],
    deps = [
        ":tensorlang",
        "//research/joint_shard/egg-c:eggc",
        "@com_google_googletest//:gtest_main",
        "@llvm-project//mlir:IR",
        "@stablehlo//:stablehlo_ops",
    ],
    linkstatic = True,
)

cc_test(
    name = "semantic_rewrite_test",
    srcs = ["semantic_rewrite_test.cc"],
    deps = [
        ":tensorlang",
        "//research/joint_shard/egg-c:eggc",
        "@com_google_googletest//:gtest_main",
        "@llvm-project//mlir:IR",
    ],
    linkstatic = True,
)

cc_test(
    name = "tensorlang_test",
    srcs = ["tensorlang_test.cc"],
    deps = [
        ":tensorlang",
        "//research/joint_shard/egg-c:eggc",
        "@com_google_googletest//:gtest_main",
        "@llvm-project//mlir:IR",
    ],
    linkstatic = True,
)
